import Head from 'next/head'
import Layout from '../components/Layout'
import { MainContainer } from '../components/commons'
import { Canvas } from '@react-three/fiber'
import { useState, useEffect, useRef } from 'react'
import { Box, CameraShake, MapControls, OrbitControls, OrthographicCamera, PerspectiveCamera, PointerLockControls } from '@react-three/drei'
import { AmbientLight, Mesh, Object3D, Vector3 } from 'three'



export default function Home() {
  const [pointer, setPointer] = useState<Vector3>(new Vector3(0, 0, 0))

  return (
    <Layout>
      
        <Head>
          <title>草</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <MainContainer>
        <Canvas>
          <mesh onClick={e => console.log(e)}>

          
            <CameraMovement pointer={pointer} />
          </mesh>
        </Canvas>
      </MainContainer>
        
    </Layout>
  )
}


const CameraMovement = ({pointer}: { pointer: Vector3}) => {
  const boxRef = useRef<Object3D>(null!)
  useEffect(() => {
    boxRef.current.lookAt(pointer)
  }, [pointer])
  return (
    <>
    
      <Box ref={boxRef} args={[5, 5, 5]} position={[0, 0, -4]} onClick={() => console.log(pointer)}>
        <meshPhongMaterial wireframe />
      </Box>
      <ambientLight intensity={0.5} />
      <MapControls />
      
      
    </>
  )
}