/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SkellyArm(props:any) {
  const group = useRef()
  const { nodes, material } = useGLTF(
    '/models/Model.gltf'
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes['pinky-finger-tip']} />
      <primitive object={nodes['pinky-finger-phalanx-distal']} />
      <primitive object={nodes['pinky-finger-phalanx-intermediate']} />
      <primitive object={nodes['pinky-finger-phalanx-proximal']} />
      <primitive object={nodes['pinky-finger-metacarpal']} />
      <primitive object={nodes['ring-finger-tip']} />
      <primitive object={nodes['ring-finger-phalanx-distal']} />
      <primitive object={nodes['ring-finger-phalanx-intermediate']} />
      <primitive object={nodes['ring-finger-phalanx-proximal']} />
      <primitive object={nodes['ring-finger-metacarpal']} />
      <primitive object={nodes['middle-finger-tip']} />
      <primitive object={nodes['middle-finger-phalanx-distal']} />
      <primitive object={nodes['middle-finger-phalanx-intermediate']} />
      <primitive object={nodes['middle-finger-phalanx-proximal']} />
      <primitive object={nodes['middle-finger-metacarpal']} />
      <primitive object={nodes['index-finger-tip']} />
      <primitive object={nodes['index-finger-phalanx-distal']} />
      <primitive object={nodes['index-finger-phalanx-intermediate']} />
      <primitive object={nodes['index-finger-phalanx-proximal']} />
      <primitive object={nodes['index-finger-metacarpal']} />
      <primitive object={nodes['thumb-tip']} />
      <primitive object={nodes['thumb-phalanx-distal']} />
      <primitive object={nodes['thumb-phalanx-proximal']} />
      <primitive object={nodes['thumb-metacarpal']} />
      <primitive object={nodes.wrist} />
      <skinnedMesh
        geometry={nodes.Skeleton001.geometry}
        material={nodes.Skeleton001.material}
        skeleton={nodes.Skeleton001.skeleton}
      />
    </group>
  )
}

useGLTF.preload(
  '/models/Model.gltf'
)
